server:
  port: 1010

spring:
  application:
    name: storage-microservice
  cloud:
    aws:
      s3:
        region: us-east-1
      credentials:
        secret-key: ${AWS_SECRET_KEY:1234}
        access-key: ${AWS_ACCESS_KEY:1234}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/market}
    username: ${DATASOURCE_USERNAME:arturk}
    password: ${DATASOURCE_PWD:arturk2308}
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    default-schema: storage
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: storage
reports:
  location: storage-ms/target/generated-files/