server:
  port: 1030

spring:
  application:
    name: order-microservice
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: arturk
      password: arturk2308
      database: market
  jpa:
    hibernate:
      ddl-auto: create-drop

kafka:
  bootstrap-server: ${KAFKA_BOOTSTRAP_SERVER:127.0.0.1:29092}
  group-id: order-ms-dev
  topic-name:
    order_created: order_created_dev
    storage_event: storage_event_dev
    payment_event: payment_event_dev
    storage_recovery_event: storage_recovery_event_dev
