server:
  port: 1020

spring:
  application:
    name: customer-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/market}
    username: ${DATASOURCE_USERNAME:arturk}
    password: ${DATASOURCE_PWD:arturk2308}
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    default-schema: customer
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: customer
kafka:
  bootstrap-server: ${KAFKA_BOOTSTRAP_SERVER:127.0.0.1:29092}
  group-id: customer-ms-dev
  topic-name:
    storage_available: storage_available_dev
    payment_event: payment_event_dev
storage-ms:
  product:
    url: ${STORAGE_MS_PRODUCT_URL:http://127.0.0.1:1010/api/v4/product}